export const FETCH_SURA_REQUEST = "FETCH_SURA_REQUEST";
export const FETCH_SURA_SUCCESS = "FETCH_SURA_SUCCESS";
export const FETCH_SURA_FAILURE = "FETCH_SURA_FAILURE";
export const FILTER_SURA = "FILTER_SURA";
export const SEARCH_SURA = "SEARCH_SURA";
